author: Jörn-Thorben Hinz
name: Build Debian packages
description: Build Debian packages with dpkg-buildpackage in a flexible environment.
inputs:
  apt_opts:
    description: Options to be passed to apt-get
    required: false
  artifacts_dir:
    default: debian/artifacts
    description: Directory path relative to $GITHUB_WORKSPACE to place the built packages in
    required: false
  buildpackage_opts:
    description: Options to be passed to dpkg-buildpackage
    required: false
  docker_image:
    default: debian:stable-slim
    description: Name of a Docker image to build inside
    required: false
  extra_build_deps:
    description: Extra packages to be installed as build dependencies
    required: false
  source_dir:
    default: ''
    description: Path relative to $GITHUB_WORKSPACE that contains the package sources
    required: false
runs:
  using: composite
  steps:
    - run: ${{ github.action_path }}/scripts/run.sh
      shell: bash
branding:
  color: red
  icon: package
