author: 'Jörn-Thorben Hinz'
name: 'Build a Debian package'
description: 'Build a Debian package for any distribution using them'
inputs:
  args:
    description: 'Options to be passed to dpkg-buildpackage'
    required: false
  docker-image:
    description: 'Name of a Docker image to build inside'
    required: true
outputs:
  packages:
    description: 'Space separated list of filenames of the packages built'
runs:
  using: 'composite'
  steps:
    - run: env > "$HOME/build-deb-package.env"
      shell: sh
    - run: docker run --env-file "$HOME/build-deb-package.env" --rm --volume "$GITHUB_ACTION_PATH":/github/action --volume "$GITHUB_WORKSPACE":/github/workspace --workdir /github/workspace "${{ inputs.docker-image }}" /github/action/build.sh ${{ inputs.args }}
      shell: sh
    - run: rm -f "$HOME/build-deb-package.env"
      shell: sh
branding:
  icon: 'package'
