author: 'Jörn-Thorben Hinz'
name: 'Build a Debian package'
description: 'Build a Debian package for any distribution using them'
inputs:
  args:
    description: 'Options to be passed to dpkg-buildpackage'
    required: false
  docker-image:
    description: 'Name of a Docker image to build inside'
    required: true
outputs:
  packages:
    description: 'Space separated list of filenames of the packages built'
runs:
  using: 'composite'
  steps:
    - run: env > "$HOME/build-deb-package.env"
      shell: sh
    - run: docker create --env-file "$HOME/build-deb-package.env" --name build-deb-package --tty --volume "$HOME":"$HOME" --workdir "$GITHUB_WORKSPACE" "${{ inputs.docker-image }}" cat
      shell: sh
    - run: docker cp "$GITHUB_ACTION_PATH/entrypoint.sh" build-deb-package:/
      shell: sh
    - run: docker start build-deb-package
      shell: sh
    - run: docker exec build-deb-package /entrypoint.sh ${{ inputs.args }}
      shell: sh
    - run: docker rm --force build-deb-package
      shell: sh
    - run: rm -f "$HOME/build-deb-package.env"
      shell: sh
branding:
  icon: 'package'
