author: 'Jörn-Thorben Hinz'
name: 'Build a Debian package'
description: 'Build a Debian package for any distribution using them'
inputs:
  args:
    description: 'Options to be passed to dpkg-buildpackage'
    required: false
  docker-image:
    description: 'Name of a Docker image to build inside'
    required: true
outputs:
  packages:
    description: 'Space separated list of filenames of the packages built'
runs:
  using: 'composite'
  steps:
    - run: env > "$HOME/env.list"
      shell: sh
    - run: env
      shell: sh
    - run: docker build -t build-deb-package --build-arg=BUILD_FROM="${{ inputs.docker-image }}" "$GITHUB_ACTION_PATH"
      shell: sh
    - run: docker run --rm -v"$HOME":"$HOME" --workdir "$GITHUB_WORKSPACE" --env-file "$HOME/env.list" --entrypoint env build-deb-package
      shell: sh
    - run: docker run --rm -v"$HOME":"$HOME" --workdir "$GITHUB_WORKSPACE" --env-file "$HOME/env.list" build-deb-package ${{ inputs.args }}
      shell: sh
branding:
  icon: 'package'
