author: Jörn-Thorben Hinz
name: Build a Debian package
description: Build a Debian package for any distribution using them
inputs:
  apt-opts:
    description: Options to be passed to apt-get
    required: false
  artifacts-dir:
    default: debian/artifacts
    description: Directory path relative to $GITHUB_WORKSPACE to place the built packages in
    required: false
  dbp-opts:
    description: Options to be passed to dpkg-buildpackage
    required: false
  docker-image:
    default: debian:stable-slim
    description: Name of a Docker image to build inside
    required: false
  extra-build-deps:
    description: Extra packages to be installed as build dependencies
    required: false
  source-dir:
    default: ''
    description: Path relative to $GITHUB_WORKSPACE that contains the package sources
    required: false
runs:
  using: composite
  steps:
    - env:
        BDP_APT_OPTS: ${{ inputs.apt-opts }}
        BDP_ARTIFACTS_DIR: ${{ inputs.artifacts-dir }}
        BDP_DOCKER_IMAGE: ${{ inputs.docker-image }}
        BDP_EXTRA_BUILD_DEPS: ${{ inputs.extra-build-deps }}
        BDP_SOURCE_DIR: ${{ inputs.source-dir }}
      run: $GITHUB_ACTION_PATH/run.sh
      shell: bash
branding:
  color: red
  icon: package
