on: push

jobs:
  build-deb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: .github/actions/build-deb-package
        with:
          args: --no-sign

      - uses: actions/upload-artifact@v2
        with:
          name: 'Debian packages'
          path: ../*.deb
