on: push

jobs:
  debian-bullseye-packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/build-deb-package
        env:
          DEB_BUILD_OPTIONS: noautodbgsym
        with:
          dbp-opts: --build=binary --no-sign
          docker-image: debian:bullseye-slim

      - uses: actions/upload-artifact@v2
        with:
          name: 'Debian Bullseye packages'
          path: '*.deb'

  debian-buster-packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/build-deb-package
        env:
          DEB_BUILD_OPTIONS: noautodbgsym
        with:
          dbp-opts: --build=binary --no-sign
          docker-image: debian:buster-slim

      - uses: actions/upload-artifact@v2
        with:
          name: 'Debian Buster packages'
          path: '*.deb'

  ubuntu-bionic-packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/build-deb-package
        env:
          DEB_BUILD_OPTIONS: noautodbgsym
        with:
          dbp-opts: --build=binary --no-sign
          docker-image: ubuntu:bionic

      - uses: actions/upload-artifact@v2
        with:
          name: 'Ubuntu Bionic packages'
          path: '*.deb'

  ubuntu-focal-packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/build-deb-package
        env:
          DEB_BUILD_OPTIONS: noautodbgsym
        with:
          dbp-opts: --build=binary --no-sign
          docker-image: ubuntu:focal

      - uses: actions/upload-artifact@v2
        with:
          name: 'Ubuntu Focal packages'
          path: '*.deb'
