on: push

jobs:
  build-deb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/build-deb-package
        env:
          DEB_BUILD_OPTIONS: noautodbgsym
          DPKG_COLORS: auto
          DPKG_NLS: 1
        with:
          apt-args: -t stretch-backports
          args: --no-sign
          docker-image: debian:oldstable-backports

      - uses: actions/upload-artifact@v2
        with:
          name: 'Debian packages'
          path: '*.deb'
