on: push

jobs:
  default-source-dir:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cp -r test/* .
      - uses: ./
        env:
          DEB_BUILD_OPTIONS: noautodbgsym
        with:
          buildpackage-opts: --build=binary --no-sign
      - run: |
          dpkg --info debian/artifacts/test_1_amd64.deb
          dpkg --contents debian/artifacts/test_1_amd64.deb | grep ./usr/bin/mybin
          test -f debian/artifacts/test_1_amd64.buildinfo
          test -f debian/artifacts/test_1_amd64.changes

  different-artifacts-dir:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        env:
          DEB_BUILD_OPTIONS: noautodbgsym
        with:
          artifacts-dir: my_artifacts
          buildpackage-opts: --build=binary --no-sign
          source-dir: test
      - run: |
          dpkg --info my_artifacts/test_1_amd64.deb
          dpkg --contents my_artifacts/test_1_amd64.deb | grep ./usr/bin/mybin
          test -f my_artifacts/test_1_amd64.buildinfo
          test -f my_artifacts/test_1_amd64.changes

  different-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        env:
          DEB_BUILD_OPTIONS: noautodbgsym
        with:
          buildpackage-opts: --build=binary --no-sign
          docker-image: ubuntu:latest
          source-dir: test
      - run: |
          dpkg --info debian/artifacts/test_1_amd64.deb
          dpkg --contents debian/artifacts/test_1_amd64.deb | grep ./usr/bin/mybin
          test -f debian/artifacts/test_1_amd64.buildinfo
          test -f debian/artifacts/test_1_amd64.changes

  different-host-arch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        env:
          DEB_BUILD_OPTIONS: noautodbgsym
        with:
          buildpackage-opts: --build=binary --no-sign
          host-arch: i386
          source-dir: test
      - run: |
          dpkg --info debian/artifacts/test_1_i386.deb
          dpkg --contents debian/artifacts/test_1_i386.deb | grep ./usr/bin/mybin
          test -f debian/artifacts/test_1_i386.buildinfo
          test -f debian/artifacts/test_1_i386.changes

  multiple-packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          buildpackage-opts: --build=binary --no-sign
          source-dir: test
      - run: |
          dpkg --info debian/artifacts/test_1_amd64.deb
          dpkg --info debian/artifacts/test-dbgsym_1_amd64.deb
          dpkg --contents debian/artifacts/test_1_amd64.deb | grep ./usr/bin/mybin
          dpkg --contents debian/artifacts/test-dbgsym_1_amd64.deb
          test -f debian/artifacts/test_1_amd64.buildinfo
          test -f debian/artifacts/test_1_amd64.changes

  single-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        env:
          DEB_BUILD_OPTIONS: noautodbgsym
        with:
          buildpackage-opts: --build=binary --no-sign
          source-dir: test
      - run: |
          dpkg --info debian/artifacts/test_1_amd64.deb
          dpkg --contents debian/artifacts/test_1_amd64.deb | grep ./usr/bin/mybin
          test -f debian/artifacts/test_1_amd64.buildinfo
          test -f debian/artifacts/test_1_amd64.changes
