on: push

jobs:
  different-artifacts_dir:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        env:
          DEB_BUILD_OPTIONS: noautodbgsym
        with:
          artifacts_dir: my_artifacts
          buildpackage_opts: --build=binary --no-sign
          source_dir: test
      - run: |
          dpkg --info my_artifacts/test_1_amd64.deb
          dpkg --contents my_artifacts/test_1_amd64.deb | grep ./usr/bin/mybin
          test -f my_artifacts/test_1_amd64.buildinfo
          test -f my_artifacts/test_1_amd64.changes

  different-docker_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        env:
          DEB_BUILD_OPTIONS: noautodbgsym
        with:
          buildpackage_opts: --build=binary --no-sign
          docker_image: ubuntu:latest
          source_dir: test
      - run: |
          dpkg --info debian/artifacts/test_1_amd64.deb
          dpkg --contents debian/artifacts/test_1_amd64.deb | grep ./usr/bin/mybin
          test -f debian/artifacts/test_1_amd64.buildinfo
          test -f debian/artifacts/test_1_amd64.changes

  multiple-packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          buildpackage_opts: --build=binary --no-sign
          source_dir: test
      - run: |
          dpkg --info debian/artifacts/test_1_amd64.deb
          dpkg --info debian/artifacts/test-dbgsym_1_amd64.deb
          dpkg --contents debian/artifacts/test_1_amd64.deb | grep ./usr/bin/mybin
          dpkg --contents debian/artifacts/test-dbgsym_1_amd64.deb
          test -f debian/artifacts/test_1_amd64.buildinfo
          test -f debian/artifacts/test_1_amd64.changes

  single-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        env:
          DEB_BUILD_OPTIONS: noautodbgsym
        with:
          buildpackage_opts: --build=binary --no-sign
          source_dir: test
      - run: |
          dpkg --info debian/artifacts/test_1_amd64.deb
          dpkg --contents debian/artifacts/test_1_amd64.deb | grep ./usr/bin/mybin
          test -f debian/artifacts/test_1_amd64.buildinfo
          test -f debian/artifacts/test_1_amd64.changes
